### ISSUE TITLE
Script is failing today when attempting to connect to certain regions

### ISSUE THREAD

**Issue by wkbrd** [aws-samples/ec2-classic-resource-finder#12]
Script is failing today when attempting to connect to certain regions

`Could not connect to the endpoint URL: "https://datapipeline.us-west-1.amazonaws.com/"

Could not connect to the endpoint URL: "https://datapipeline.ap-southeast-1.amazonaws.com/"

Could not connect to the endpoint URL: "https://datapipeline.sa-east-1.amazonaws.com/"
`

Interestingly, it seems that I am unable to perform an nslookup for the three DNS names above.  Other regions seem to resolve properly.  Are others experiencing this issue?

**Comment by scmrr** [comment]
This is expected and noted in the README as datapipeline does not support those regions (and therefore does not have endpoints there).
