### ISSUE TITLE
ElasticBeanstalk Environments with Classic LBs are not detected

### ISSUE THREAD

**Issue by RefreshingWater** [aws-samples/ec2-classic-resource-finder#16]
The resource finder does not notify you when your ElasticBeanstalk Environments contain an active classic loadbalancer only if they aren't in a VPC. Since all CLBs are going away per Amazon direct support inquiry, the script should be updated to notice that your environment it utilizing one. 

The Classic LBs also do not show up in Classic_CLBs.csv.

**Comment by scmrr** [comment]
Hello, I just want to clarify, Classic Load Balancers which are not running in a VPC (and thus running on EC2-Classic) are being retired as part of this. Classic Load Balancers which are in a VPC are not being retired as part of the EC2-Classic retirement. 

Can you please confirm, you are not seeing ElasticBeanstalk Environments with a Classic Load Balancer in EC2-Classic (not in a VPC) being missed?

**Comment by RefreshingWater** [comment]
We were informed otherwise that all Classic LBs were being retired not just ones not in a VPC. Since that sounds to be not the case I'll close.
