### ISSUE TITLE
More details for Unknown status

### ISSUE THREAD

**Issue by gabriel-tessier** [aws-samples/ec2-classic-resource-finder#17]
Hi,

In the Outputs section of the README for the Classic_Platform_Status.csv file may need to also include the "Unknown" status with a recall to check the errors.txt file.
Or/And when the script end and errors.txt file exist write a warning, if you run the script you only see green mark even if all fail which give feeling that all is ok.

Hope it help.

**Comment by scmrr** [comment]
Thank you for the feedback. I am working on a new iteration that addresses several comments including this.
