### ISSUE TITLE
More information about default security groups

### ISSUE THREAD

**Issue by gabriel-tessier** [aws-samples/ec2-classic-resource-finder#18]
Hi,

There's some missing information on how to deal with default security groups.
After several run and cleanup all the csv files were empty (need to remove the files between each run as the script append data) except Classic_SGs.csv which list several SG in different region but all are default and when trying to delete in the interface this message is displayed:

> This is a default security group. Default security groups cannot be deleted

If you can add some information on how to deal with this and if it's ok to request a conversion to VPC-Only for this case.

Other small improvement that may help when run the script several time, if you can append a timestamp for each line in the logs it can be helpful to see difference between the several run.

**Comment by scmrr** [comment]
Thank you for your feedback. I am work on a new iteration of the script that will address the timestamp request. 

Regarding, the default security group, you do not need to delete it to disable EC2-Classic. However, I will work to see how we can better document this. Thank you for your feedback.
