### ISSUE TITLE
Why does it flag default security groups as EC2 Classic resources?

### ISSUE THREAD

**Issue by auspicious99** [aws-samples/ec2-classic-resource-finder#22]
I ran the script, and it picked out one region to give something unusual.

Most of the CSVs are empty, except for Classic_Platform_Status.csv and Classic_SGs.csv ; so I found that Classic_SGs.csv contains a solitary security group named "default" in us-east-1, whereas I have no other resources in that region.

I saw that there is a closed issue (#18 ) where the person requested for more info on how to deal with such reports of a default security group being included in Classic_SGs.csv for no apparent reason.

Could the script be fixed instead to not include these default security groups in Classic_SGs.csv ? I don't understand why it doesn't include the default security groups in other regions, but only this particular region?

I also have a related stackoverflow question about this: https://stackoverflow.com/questions/69787759/ec2-classic-resource-that-cant-be-deleted-now-what?noredirect=1#comment123433839_69787759

**Comment by scmrr** [comment]
Hello, the security groups are more just resources you should be aware of as your migrating, but they are not active resources, and thus are not going to be impacted when disabling classic, only active resources which may use those security groups would be affected.
