### ISSUE TITLE
Why do ElasticBeanstalk environments that are Terminated show up in `Classic_ElasticBeanstalk_Applications_Environments.csv`?

### ISSUE THREAD

**Issue by roskelleycj** [aws-samples/ec2-classic-resource-finder#3]
We just started to run [this script][2] on our accounts/environments and we are noticing a 'flapping' where the tool flags issues in ElasticBeanstalk Environments not having a VPC and in each case the Environment has recently been terminated.  E.g., of course it doesn't have a VPC associated because the resources have been removed.

Looking at this [line][1] I wonder if it should be changed to only consider Environments that are `Ready`?  

[1]:  https://github.com/aws-samples/ec2-classic-resource-finder/blob/9b712acec431c7fecdb2dcb4b324abf8a2ee9eee/Classic-Resource-Finder.sh#L210
[2]:  https://github.com/aws-samples/ec2-classic-resource-finder/blob/main/Classic-Resource-Finder.sh

**Comment by roskelleycj** [comment]
BTW, I found other issues that suggest that this tool does not handle the eventually consistent natures of EC2 and ElasticBeanstalk in that multiple resources were erroneously identified and yet they were in some form of state transition.  E.g., ignore the results from the tool and everything was okay.  

This type of 'false negative' makes such a tool not very useful for an enterprise operations where there is constant CHURN in an environment.

**Comment by scmrr** [comment]
Thank you for reporting the false positive on Elastic Beanstalk. I will look at how I will work to get an update pushed that filters out for terminated environments.

**Comment by scmrr** [comment]
I have pushed a commit that excludes terminated environments. This will limit the number of false positives without introducing new possibility for false negatives.
