### ISSUE TITLE
Missing permissions for elasticloadbalancing and elasticmapreduce

### ISSUE THREAD

**Issue by JasonBarnabe** [aws-samples/ec2-classic-resource-finder#30]
Readme says I need to have these permissions:

> elasticloadbalancing:DescribeLoadBalancers
> elasticmapreduce:DescribeCluster
> elasticmapreduce:ListBootstrapActions
> elasticmapreduce:ListClusters
> elasticmapreduce:ListInstanceGroups
> opsworks:DescribeStacks

Editing my policy on the IAM Mangement Console, there doesn't seem to any service for elasticloadbalancing and elasticmapreduce (unless they're named completely differently than these keys).

In addition, when I try to add opsworks:DescribeStacks, upon saving it's not set.

When I run the tool, I get a few errors saying I'm missing:

- elasticloadbalancing:DescribeLoadBalancers
- elasticmapreduce:ListClusters
- opsworks:DescribeStacks

Not sure if this indicates these things are already retired, or I'm not using them or what.

**Comment by TheScottMo** [comment]
Hi, that syntax is written to match the IAM json, if you are searching in the visual editor tab, it is ELB, EMR and OpsWorks respectively. None of these services are retiring at this time, rather EC2 Classic networking, which all of these services currently support, is retiring, so you will only be able to create resources with these services in a VPC, or in some cases public. I hope this helps, if you're still having trouble, I suggest opening a support case with AWS Support.

**Comment by JasonBarnabe** [comment]
Thanks, I found the entries under ELB and EMR. For some reason, OpsWorks permission does not "stick" after saving, but I don't use that anyway so not concerned.
