### ISSUE TITLE
False positives on RDS instances

### ISSUE THREAD

**Issue by thecommandline** [aws-samples/ec2-classic-resource-finder#6]
The script currently checks if there are any VPC security groups attached to an RDS instance to determine if it is a classic instance or not. I believe the API call to check this must occasionally fail or be throttled and that the script does not handle this properly creating a false positive. Each time I ran the script across my organization of several hundred accounts and RDS instances I got a handful of false positives which were different each time.

**Comment by scmrr** [comment]
Thank you for reporting this error. I will look to see if I can replicate it and if so try to resolve.

**Comment by scmrr** [comment]
I have not been able to replicate it, but I have put better error logging in place in the latest commit. I do suspect there is an API error which is causing the false positive. I will continue to try to replicate but at this time havent pushed any direct fix as I don't want to introduce the possibility for a false negative.
